/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package aspect.tests;

import com.retrocheck.assertion.MonitorWith;

public class App {
    public String getGreeting() {
        return "Hello world.";
    }

    public static void main( String[] args ) {
        //Actions.getTestEvent().add(Actions::fail);
        int incremented = 0;
        try {
            incremented = TestClass.addOne(1);
        }
        catch (RuntimeException ex) {
            System.out.println("an exception did happen yes");
        }

        //new App().addTwo(incremented);

        try {
            new TestClass(1, "jeff");
        }
        catch (RuntimeException ex) {
            System.out.println("an exception in a ctor did happen yes");
        }

        for (int i = 0; i < 2; i++) {
            new TestClass(1).mutateField();
        }
    }

    @MonitorWith(AppAssertions.class)
    private int addTwo(int input) {
        int once = TestClass.addOne(input);
        int twice = TestClass.addOne(input);
        return twice;
    }
}
